### ISSUE TITLE
Generate QRCode for Laundromat

### ISSUE THREAD

**Issue by seiza** [inagua/wawash#10]
As a people
I want to see the QRCode of the Laundromat
To find it in the application

## Required
- #4 
- #7 

## Properties
- [ ] URL in the QRCode = http://wawa.sh/l/:idOrCode

## TODO
- [ ] Add the sponsor in the URL: http://wawa.sh/l/:idOrCode/sponsors/:userId
- [ ] Display the name
- [ ] Generate a PDF
