### ISSUE TITLE
Generate QRCode for Washer

### ISSUE THREAD

**Issue by seiza** [inagua/wawash#11]
As a people
I want to see the QRCode of the Washer
To find it in the application

## Required
- #5 
- #7 

## Properties
- [ ] URL in the QRCode = http://wawa.sh/w/:idOrCode

## TODO
- [ ] Add the sponsor in the URL: http://wawa.sh/w/:idOrCode/sponsors/:userId
- [ ] Display the name
- [ ] Generate a PDF
