### ISSUE TITLE
Add Laundromat

### ISSUE THREAD

**Issue by seiza** [inagua/wawash#4]
As a people
I want to add a laundromat
To see the status of the washer I (am about to) use

## Required
- #7 

## Properties
- [x] userId (creator)
- [x] code (for its URL in wawa.sh)
- [ ] name
- [ ] address (:address1, :address2, :zip, :city, :country)
- [x] geoloc
- [x] description
- [ ] hours
- [ ] pictures
- [ ] social (:phone, :email, :web...)

## TODO
- [ ] Each property can be statued by any user
- [ ] Prevent spamming (create numerous creations... Should be on site ?)
- [ ] Create a "laundromat.creation" event
