### ISSUE TITLE
Add Washer / Dryer

### ISSUE THREAD

**Issue by seiza** [inagua/wawash#5]
As a people
I want to add a Washer (Dryer)
To set and follow its status

## Required
- #7 
- #4 (Laundromat should be found)

## See also
- #6 

## Properties
- [x] userId (creator)
- [x] laundromatId
- [ ] (generated) nickname => code (for its URL... Generated?)
- [x] name
- [ ] kind (washer, dryer, dual)
- [x] brand
- [x] model
- [x] description
- [x] programs
- [x] pictures
- [ ] URL / social networks
- [x] capacity
- [x] price(s)

## TODO
- [ ] Each property can be statued by any user
- [ ] Prevent spamming (create numerous creations... Should be on site ?)
- [ ] Create a "washer.creation" event
