### ISSUE TITLE
Set Washer status

### ISSUE THREAD

**Issue by seiza** [inagua/wawash#6]
As a people
I want to set the status of the washer I used
To follow it and see how long is remaining

## Properties

- [x] date
- [ ] washerId
- [x] userId
- [x] usedById
- [ ] status: `ongoing` (remaining time), `occupied`, `empty`, `ooo` (Out Of Order)
- [x] remainingMinutes

## Required
- #7 
- #5 

## TODO
- [ ] Enum for status
- [ ] Check user and washer exist
- [ ] Send a event `washer.status`
