### ISSUE TITLE
Create account and connect

### ISSUE THREAD

**Issue by seiza** [inagua/wawash#7]
As a person
I want to create my account and connect to the app
To set the Washer status (#6)

## See also
- #6 

## Properties
- [ ] status
- [x] username
- [ ] password
- [ ] salt
- [ ] email
- [x] firstName
- [x] lastName
- [x] pictures
- [ ] socials: {type, account}

## TODO
- [ ] Use [passportjs.org](http://www.passportjs.org/)
- [ ] Email confirmation (CREATING => ACTIVE)
- [ ] Use salt, and encrypt password
- [ ] Accept social networks
